language: php
matrix:
  include:
    - php: 7.3
    - php: 7.4

sudo: false
before_install:
  - export NEOS_TARGET_VERSION=5.3
  - cd ..
  - git clone https://github.com/neos/neos-base-distribution.git -b ${NEOS_TARGET_VERSION}
  - cd neos-base-distribution
  - composer require --no-update --no-interaction punktde/editconflictprevention
install:
  - composer install --no-interaction
  - cd ..
  - rm -rf neos-base-distribution/Packages/Application/PunktDe.EditConflictPrevention
  - mv editconflictprevention neos-base-distribution/Packages/Application/PunktDe.EditConflictPrevention
  - cd neos-base-distribution
script:
  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/PunktDe.EditConflictPrevention/Tests/Functional
